<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Counter" Id="{012b8ed0-2a5c-4bc2-bd74-056604d88c1c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Counter
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="AddTwo" Id="{2fd73b10-3d6d-4b49-8abc-ef2b87de2173}">
      <Declaration><![CDATA[METHOD AddTwo : DINT
VAR_INPUT
    In1 : DINT;
    In2 : DINT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[AddTwo := In1 + In2;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>